### ISSUE TITLE
[FEATURE]: Add project scripts

### ISSUE THREAD

**Issue by daniel-mizsak** [daniel-mizsak/python-package-template#25]
### Feature description

Many command line application use entry points defined in `pyproject.toml` to assign a command to a special call within the package.

Many of my other works also use this, so it would make sense to have it here as well. :)

It should look something like:
```toml
[project.scripts]
python-package-command = "python_package_template.main:main"
```
