### ISSUE TITLE
[FEATURE]: Coverage settings

### ISSUE THREAD

**Issue by daniel-mizsak** [daniel-mizsak/python-package-template#26]
### Feature description

Currently all the settings for the code `coverage` tool are set up part of `pytest`.

But since coverage is not running some special lines, for example:
```python
if TYPE_CHECKING:
    from collections.abc import Generator  # <-- This is not checked by coverage
    from pathlib import Path  # <-- This is not checked by coverage
```

It could make sense to extend `pyproject.toml`, with something like the following:
```toml
# Coverage
[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:"]
```

So that code coverage will not be reduced because of type checking.
