### ISSUE TITLE
Reduce frequency of pre-commit autoupdates

### ISSUE THREAD

**Issue by daniel-mizsak** [daniel-mizsak/python-package-template#36]
Since the project is not using many pre-commit hooks and it is mostly only ruff that gets updated it would make sense to reduce the update frequency to monthly.

Is can be done by adding the following lines to .pre-commit-config.yaml:
```yaml
# pre-commit ci
ci:
  autoupdate_schedule: monthly
```

Maybe even [look into](https://pre-commit.ci/) further pre-commit ci customizations?
